---
# Define Ansible collection requirements here
collections:
  - name: ansible.posix
  - name: ansible.utils
  - name: kubernetes.core
  - name: community.okd
  - name: community.general
  - name: amazon.aws
  - name: rhvp.cluster_utils
    source: https://github.com/validatedpatterns/rhvp.cluster_utils.git
    type: git
    version: v1
