---
ignored:
  # Last USER should not be root
  - DL3002
  # Always tag the version of an image explicitly
  - DL3006
  # Using latest is prone to errors if the image will ever update. Pin the
  # version explicitly to a release tag
  - DL3007
  # Specify version with `dnf install -y <package>-<version>`.
  - DL3041
  # Pin versions in pip. Instead of `pip install <package>` use `pip install
  - DL3013
